SELECT DISTINCT(CITY)
FROM STATION
WHERE REGEXP_LIKE (UPPER(CITY), '^[AEIOU]')
  AND REGEXP_LIKE (UPPER(CITY), '[AEIOU]$');


-- 

SELECT DISTINCT city
FROM station
WHERE UPPER(SUBSTR(city,1,1)) IN ('A','E', 'I','O','U')
    AND UPPER(SUBSTR(city, -1)) IN ('A','E','I', 'O','U')